### ISSUE TITLE
As a User, I want to take a quiz, to learn.

### ISSUE THREAD

**Issue by Droggelbecher92** [Droggelbecher92/Kirschbaum#23]
Related issues:

- [ ] #17 Learn how to use material ui
- [ ] #10 Data structure
- [ ] #11 create DB tables
- [ ] #15 add some questions
- [ ] #7 Make the Question Page
- [ ] #25 Get the questions
- [ ] #19 Show the question 
- [ ] #24 Check if Question is right
- [ ] #26 save the results
- [ ] #6 Make the Results Page

**Comment by Droggelbecher92** [comment]
Related issues:

- [ ] #17 Learn how to use material ui
- [ ] #10 Data structure
- [ ] #11 create DB tables
- [ ] #15 add some questions
- [ ] #7 Make the Question Page
- [ ] #24 Check if Question is right
- [ ] #13 Add some endpoints
- [ ] #6 Make the Results Page
- [ ] #13 Add some more endpoints
