### ISSUE TITLE
As a User, I want to filter which kind of questions-category I want to train, to train specific content.

### ISSUE THREAD

**Issue by Droggelbecher92** [Droggelbecher92/Kirschbaum#35]
Related issues:

- [ ] #8 Make Home-Screen
- [ ] #36 Ad new endpoints
- [ ] #40 get category-names
- [ ] #38 show the tiles with each category
- [ ] #39 filter by category
- [ ] #37 Return filtered
